### ISSUE TITLE
Create game events and their locations on the board (p=2)

### ISSUE THREAD

**Issue by nooc** [nooc/ruby_scientists#8]
All positions on the boars can have events.
Figure out which positions have events and what they are.

Example

Position 5: Move random steps forward.
Position 10: Go back 2 steps.
etc..

**Comment by dimialexmost** [comment]
1. får man i tärning "6" tre gånger i rad = you won
2. Position 13 "glömt köpa <s>whisky</s> cola= go back 6 steps "till kiosk"
3. får man "1" i första kast = go 5 steps forward
4. Position 10 ger rätt till "att tanka rymdskepp" - gör två kast till. 
5. Position 15 - "utomjordingar gränskontroll" - kastar ut jämnt=kör vidare när din nästa tur, kastar ut udda=hoppa över två drag (när det är 2+ spelare)
6. Position 18 - fel i motorn = hoppa över 1 drag
7. Position 20 trögt magnetfältet - om nästa kast är udda resultat =-1 steps, om nästa kast är jämnt resultat / 2  steps
8.  Position 25 "längtan efter hem" - go back 10 steps
9. Position 30 "svart hål" - börja från början
10. Position 35 "vänligt bemötande" - får extra kast
11. Position 37 "välkommen till Stora magellanska molnet"
